const state = { root: 'G:\\vrc素材', assets: [], selected: null, filter: 'all', query: '', pendingCategory: null, importedPaths: new Set() };
const $ = (selector) => document.querySelector(selector);
document.querySelector('.rail-btn[data-filter="all"]').textContent = '待整理';
document.querySelector('.rail-btn[data-filter="06_Avatar本体"]').textContent = '模型';
document.querySelector('.rail-btn[data-filter="91_非VRC内容"]').style.display = 'none';
document.querySelector('.rail-btn[data-filter="legacy"]').style.display = 'none';
document.querySelector('.rail-btn[data-filter="90_待确认"]').insertAdjacentHTML('beforebegin','<button class="rail-btn" data-filter="09_ERP内容">ERP</button>');
const categoryOptions = ['01_道具','02_衣服','03_头发','04_妆容','05_功能插件','06_Avatar本体','07_场景与地图','08_贴图与材质','09_ERP内容','90_待确认','91_非VRC内容'];

function esc(value='') { const div=document.createElement('div'); div.textContent=value; return div.innerHTML; }
function fileUrl(filePath, version='') { return `file:///${encodeURI(filePath.replaceAll('\\','/'))}${version ? `?v=${encodeURIComponent(version)}` : ''}`; }
function coverSource(asset, visited = new Set()) {
  if (!asset || visited.has(asset.fullPath)) return null;
  visited.add(asset.fullPath);
  if (asset.useDefaultCover) return null;
  const ownCover = asset.previewPath || asset.booth?.cachedImagePath || null;
  if (ownCover) return ownCover;
  const parent = asset.parentPath ? state.assets.find(item => item.fullPath === asset.parentPath) : null;
  return parent ? coverSource(parent, visited) : null;
}
function icon(asset) { return asset.kind.replace('压缩包','ARCHIVE').replace('Unity 包','UNITY').replace('图片','IMAGE').slice(0,10).toUpperCase(); }
const DEFAULT_COVERS = {
  '01_道具':['PROP','道具'], '02_衣服':['OUTFIT','衣服'], '03_头发':['HAIR','头发'], '04_妆容':['MAKEUP','妆容'],
  '05_功能插件':['SYSTEM','功能插件'], '06_Avatar本体':['AVATAR','Avatar 本体'], '07_场景与地图':['WORLD','场景 / 地图'], '08_贴图与材质':['MATERIAL','贴图 / 材质'], '09_ERP内容':['ERP','ERP 内容'],
  '01_VRC地图素材':['WORLD','场景 / 地图'], '02_Avatar素材':['AVATAR','Avatar 素材'], '03_通用3D模型与武器':['PROP','3D 模型 / 武器'], '04_当前房屋工程':['WORLD','场景工程'], '05_创作工具与AI':['SYSTEM','创作工具'], '07_贴图PSD与参考':['MATERIAL','贴图 / 参考'], '99_重复文件候选':['ARCHIVE','待处理素材']
};
const VIEW_TITLES = {
  all:'待整理素材', '01_道具':'道具素材', '02_衣服':'衣服素材', '03_头发':'头发素材', '04_妆容':'妆容素材',
  '05_功能插件':'功能插件', '06_Avatar本体':'Avatar 本体', '07_场景与地图':'场景与地图', '08_贴图与材质':'贴图与材质', '09_ERP内容':'ERP 内容',
  '90_待确认':'待确认素材', '91_非VRC内容':'非 VRC 内容', legacy:'旧分类素材'
};
VIEW_TITLES['06_Avatar本体']='模型本体';
VIEW_TITLES['02_Avatar素材']='模型素材';
function coverMarkup(asset) { const cover=coverSource(asset); if(cover) return `<img src="${fileUrl(cover)}" alt="${esc(asset.name)} 预览">`; const fallback=DEFAULT_COVERS[asset.category]; return fallback ? `<div class="default-cover"><span>${fallback[0]}</span><small>${fallback[1]} / 未绑定 BOOTH 封面</small></div>` : `<span>${icon(asset)}</span>`; }
function visibleAssets() { return state.assets.filter(a => (state.filter === 'all' ? !a.confirmed && a.category !== '91_非VRC内容' : state.filter === 'legacy' ? a.isLegacy : a.category === state.filter) && `${a.name} ${a.kind} ${a.category}`.toLowerCase().includes(state.query.toLowerCase())); }
function familyTokens(name) { return [...new Set((name.normalize('NFKC').toLowerCase().match(/[a-z][a-z0-9]{4,}/g) || []).filter(token => !['interactive','addon','avatar','unity','package','system','model'].includes(token)))]; }
function sameProductSignal(firstName,secondName){const first=familyTokens(firstName).filter(token=>token.length>=7);const second=new Set(familyTokens(secondName).filter(token=>token.length>=7));const shared=first.filter(token=>second.has(token));return shared.some(token=>token.length>=10)||shared.length>=2;}
function relatedBoothCandidates(asset) { if(!familyTokens(asset.name).length) return []; return state.assets.filter(item=>item.id!==asset.id&&item.booth?.matched&&item.booth?.itemUrl&&sameProductSignal(asset.name,item.name)).slice(0,3).map(item=>({name:item.name,title:item.booth.title,itemUrl:item.booth.itemUrl})); }
function localReferenceCandidates(asset) { if(!familyTokens(asset.name).length) return []; return state.assets.filter(item=>item.id!==asset.id&&item.localReference&&item.booth?.matched&&item.booth?.itemUrl&&sameProductSignal(asset.name,item.name)).slice(0,3).map(item=>({name:item.name,title:item.booth.title,itemUrl:item.booth.itemUrl})); }
const nativeBoothSearch=window.assetApi.boothSearch.bind(window.assetApi);
window.assetApi.boothSearch=(name,options={})=>state.selected?nativeBoothSearch(name,{...options,rootPath:state.root,relatedBooth:relatedBoothCandidates(state.selected),localReferences:localReferenceCandidates(state.selected)}):nativeBoothSearch(name,options);
function searchEvidenceMarkup(result) {
  const evidence=result.searchEvidence;
  if(!evidence) return '';
  const terms=(evidence.terms||[]).map(term=>`<code>${esc(term)}</code>`).join('') || '<em>无</em>';
  const related=(evidence.relatedPackages||[]).map(name=>`<li>${esc(name)}</li>`).join('');
  const llm=evidence.localConsensus ? `<li><b>本地同族包共识：</b>${evidence.localConsensus.count} 份已确认包指向同一 BOOTH 商品，已优先采用，LLM 不参与覆盖。</li>` : evidence.trustedReference ? `<li><b>人工本地参考：</b>已采用「${esc(evidence.trustedReference.name)}」确认过的 BOOTH 商品，LLM 不参与覆盖。</li>` : evidence.llm ? `<li><b>LLM 判别：</b>${evidence.llm.index >= 0 ? `候选 #${evidence.llm.index+1}` : '未确认任何候选'}；置信度 ${Math.round((Number(evidence.llm.confidence)||0)*100)}%${evidence.llm.reason?`；${esc(evidence.llm.reason)}`:''}</li>` : '<li><b>LLM 判别：</b>本次未启用</li>';
  const candidateEvidence=(result.candidates||[]).map((item,index)=>`<li><b>#${index+1} ${esc(item.title)}</b><span>总分 ${Math.round(item.score||0)}${item.matchTerms?.length?` · 检索词：${esc(item.matchTerms.join(' / '))}`:''}${item.matchedTokens?.length?` · 标题命中：${esc(item.matchedTokens.join(', '))}`:''}${item.contentMatches?.length?` · 内容物：${esc(item.contentMatches.join(', '))}`:''}${item.creatorMatches?.length?` · 作者线索：${esc(item.creatorMatches.join(', '))}`:''}${item.localRelatedName?` · 同族包：${esc(item.localRelatedName)}`:''}</span></li>`).join('');
  return `<details class="search-evidence"><summary>查看检索证据与候选分数</summary><div class="evidence-body"><p><b>实际检索词</b>${terms}</p>${evidence.productId?`<p><b>BOOTH 编号</b><code>${esc(evidence.productId)}</code></p>`:''}${related?`<p><b>本地同族包</b></p><ul>${related}</ul>`:''}<ul>${llm}</ul>${candidateEvidence?`<p><b>候选证据</b></p><ol>${candidateEvidence}</ol>`:''}</div></details>`;
}
function renderGrid() {
  const assets = visibleAssets(); $('#count').textContent = assets.length;
  document.querySelector('.archive-head h2').textContent = VIEW_TITLES[state.filter] || '素材浏览';
  $('#assetGrid').innerHTML = assets.length ? assets.map(a => `<button class="asset ${state.selected?.id===a.id?'selected':''}" data-id="${a.id}" aria-label="查看 ${esc(a.name)}"><div class="cover">${coverMarkup(a)}<small class="type">${esc(a.kind)}</small></div><div class="asset-info"><div class="asset-name">${esc(a.name)}</div><div class="asset-meta"><span>${esc(a.size)}</span><span>${esc(a.modified)}</span></div><span class="tag">${esc(a.category)}</span></div></button>`).join('') : '<p>没有符合条件的素材。</p>';
  document.querySelectorAll('.asset').forEach(el=>{el.addEventListener('click',()=>{ state.selected=state.assets.find(a=>a.id===el.dataset.id); renderGrid(); renderDossier(); });el.addEventListener('dblclick',()=>window.assetApi.showInFolder(state.assets.find(a=>a.id===el.dataset.id).fullPath));});
}
function renderDossier() {
  const asset = state.selected;
  if (!asset) return;
  const detailCover = coverSource(asset); const storedBooth=asset.booth?.itemUrl||''; $('#dossier').innerHTML = `<p class="detail-label">DOSSIER / ${esc(asset.kind)}</p><h2 class="detail-title">${esc(asset.name)}</h2><div class="detail-preview">${detailCover ? `<img src="${fileUrl(detailCover)}" alt="${esc(asset.name)} 预览">` : `<span>${icon(asset)}</span>`}</div><div class="facts"><div class="fact"><b>原始文件</b><span>${esc(asset.rawName)}</span></div><div class="fact"><b>大小</b><span>${esc(asset.size)}</span></div><div class="fact"><b>当前建议</b><span>${esc(asset.category)}</span></div>${storedBooth?`<div class="fact"><b>BOOTH</b><button id="openStoredBooth">查看商品页</button></div>`:''}</div><section class="candidate" id="boothCandidate"><span class="detail-label">BOOTH / NOT CHECKED</span><p>尚未检索。会以素材名作为关键词访问 BOOTH；低置信度匹配仍需人工确认。</p><label class="detail-label">手动 BOOTH 链接<input id="boothLinkInput" placeholder="https://booth.pm/ja/items/…"></label><button id="applyBoothLink">抓取链接中的商品与预览图</button></section><div class="actions"><button id="boothSearch">在 BOOTH 查找候选</button><button id="openPath">打开原文件位置</button><label class="detail-label">归档分类<select class="move-select" id="categorySelect">${categoryOptions.map(c=>`<option ${c===asset.category?'selected':''}>${c}</option>`).join('')}</select></label><label class="detail-label">其它链接<input id="externalLink" placeholder="粘贴链接"></label><button id="saveLink">保存链接</button><button id="saveCategory">保存分类标记</button><button class="primary" id="requestMove">确认并移动原文件</button></div>`;
  if(!detailCover && DEFAULT_COVERS[asset.category]) $('#dossier .detail-preview').innerHTML=coverMarkup(asset);
  const isAvatarModel=asset.category==='06_Avatar本体'||asset.category==='02_Avatar素材';
  $('#dossier .actions').insertAdjacentHTML('afterbegin',`<div class="manual-search-links"><button id="openBoothManual">在 BOOTH 手动搜索</button><button id="openBoothplorerManual">${isAvatarModel?'打开 Boothplorer 模型浏览':'打开 Boothplorer 素材浏览'}</button></div>`);
  if(asset.booth?.matched) $('#boothCandidate').innerHTML=`<span class="detail-label">BOOTH / CONFIRMED</span><p>已绑定：${esc(asset.booth.title || 'BOOTH 商品')}。可使用下方按钮重新检索或手动替换链接。</p><button id="toggleLocalReference" class="reference-action">${asset.localReference?'移出本地参考库':'加入本地参考库'}</button><label class="detail-label">手动 BOOTH 链接<input id="boothLinkInput" placeholder="https://booth.pm/ja/items/…"></label><button id="applyBoothLink">抓取链接中的商品与预览图</button>`;
  $('#boothCandidate').insertAdjacentHTML('beforeend','<button id="useDefaultCover" class="default-cover-action">↺ 切回分类默认封面</button>');
  $('#boothCandidate').insertAdjacentHTML('beforeend',`<label class="detail-label">已知标签<select id="llmTag" class="move-select"><option value="">不指定</option>${['道具','衣服','头发','妆容','功能插件','Avatar本体','场景地图','贴图材质','ERP内容'].map(t=>`<option ${asset.llmHints?.tag===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="toggle"><input id="useLlmForSearch" type="checkbox" ${asset.llmHints?.useLlm?'checked':''}> 本次检索使用 LLM 判别</label>`);
  if($('#useDefaultCover')) $('#useDefaultCover').addEventListener('click',async()=>{asset.booth=null;asset.useDefaultCover=true;await window.assetApi.saveClassifications(state.root,state.assets);$('#scanStatus').textContent='BOOTH BINDING CLEARED / USING CATEGORY COVER';renderGrid();renderDossier();});
  if($('#toggleLocalReference')) $('#toggleLocalReference').addEventListener('click',async()=>{asset.localReference=!asset.localReference;await window.assetApi.saveClassifications(state.root,state.assets);$('#scanStatus').textContent=asset.localReference?'LOCAL REFERENCE SAVED / 仅保存在本机':'LOCAL REFERENCE REMOVED';renderDossier();});
  const parentAsset=state.assets.find(item=>item.fullPath===asset.parentPath); const children=state.assets.filter(item=>item.parentPath===asset.fullPath); $('#dossier').insertAdjacentHTML('beforeend',`<section class="candidate relation"><span class="detail-label">RELATION / 附属关联</span>${parentAsset?`<p>所属主素材：<button id="openParent">${esc(parentAsset.name)}</button></p>`:''}${children.length?`<p>关联附属：${children.map(item=>esc(item.name)).join('、')}</p>`:''}<label class="detail-label">关联到主素材<select id="parentSelect" class="move-select"><option value="">未关联</option>${state.assets.filter(item=>item.id!==asset.id).map(item=>`<option value="${esc(item.fullPath)}" ${item.fullPath===asset.parentPath?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label><button id="saveRelation">保存关联</button></section>`);
  const parentSelect=$('#parentSelect'); const emptyParentOption=parentSelect.options[0].cloneNode(true); const parentOptions=[...parentSelect.options].slice(1).sort((a,b)=>a.textContent.localeCompare(b.textContent,'zh-Hans-CN-u-co-pinyin',{numeric:true,sensitivity:'base'})); let parentSelection=parentSelect.value; const refreshParentOptions=(query='')=>{const normalized=query.trim().toLowerCase();parentSelect.replaceChildren(emptyParentOption.cloneNode(true),...parentOptions.filter(option=>option.textContent.toLowerCase().includes(normalized)));if([...parentSelect.options].some(option=>option.value===parentSelection))parentSelect.value=parentSelection;}; document.querySelector('.relation').insertAdjacentHTML('afterbegin','<label class="detail-label parent-search">搜索主素材<input id="parentFilter" type="search" placeholder="按名称或首字母筛选"></label>'); refreshParentOptions(); parentSelect.addEventListener('change',()=>{parentSelection=parentSelect.value;}); $('#parentFilter').addEventListener('input',event=>refreshParentOptions(event.target.value));
  if(children.length){document.querySelector('.relation').insertAdjacentHTML('beforeend',`<div class="related-items">${children.map(item=>`<button class="related-child" data-child-id="${item.id}">${esc(item.name)}</button>`).join('')}</div>`);document.querySelectorAll('.related-child').forEach(button=>button.addEventListener('click',()=>{state.selected=state.assets.find(item=>item.id===button.dataset.childId);renderGrid();renderDossier();}));}
  $('#boothSearch').addEventListener('click', async () => { asset.llmHints={useLlm:$('#useLlmForSearch').checked,tag:$('#llmTag').value}; $('#boothCandidate').innerHTML='<span class="detail-label">BOOTH / SEARCHING</span><p>正在查找商品与缩略图…</p>'; const result=await window.assetApi.boothSearch(asset.name,asset.llmHints); asset.booth=result; await window.assetApi.saveClassifications(state.root,state.assets); renderGrid(); const preview = result.cachedImagePath ? fileUrl(result.cachedImagePath) : result.image; const picks=(result.candidates||[]).map((c,i)=>`<button class="candidate-pick" data-url="${esc(c.url)}">${c.image?`<img src="${esc(c.image)}" alt="">`:''}<span>${i+1}. ${esc(c.title)} <small>评分 ${Math.round(c.score||0)}</small></span></button>`).join(''); $('#boothCandidate').innerHTML=`<span class="detail-label">BOOTH / RESULT</span><p>${esc(result.status)}</p>${preview?`<img src="${esc(preview)}" alt="BOOTH 搜索预览">`:''}${picks?`<p>点选候选封面确认：</p><div class="candidate-options">${picks}</div>`:''}${searchEvidenceMarkup(result)}<button id="openBooth">打开 BOOTH 搜索结果</button>`; $('#openBooth').addEventListener('click',()=>window.assetApi.openExternal(result.searchUrl)); document.querySelectorAll('.candidate-pick').forEach(button=>button.addEventListener('click',async()=>{const selected=await window.assetApi.boothSearch(button.dataset.url,{useLlm:false});asset.booth=selected;asset.useDefaultCover=false;asset.coverRevision=Date.now();asset.localReference=true;await window.assetApi.saveClassifications(state.root,state.assets);$('#scanStatus').textContent='BOOTH CONFIRMED / LOCAL REFERENCE SAVED';renderGrid();renderDossier();})); });
  $('#openBoothManual').addEventListener('click',()=>window.assetApi.openExternal(`https://booth.pm/ja/search/${encodeURIComponent(asset.name)}?sort=new&tags%5B%5D=VRChat`));
  if($('#openBoothplorerManual')) $('#openBoothplorerManual').addEventListener('click',()=>window.assetApi.openExternal(`${isAvatarModel?'https://boothplorer.com/avatars':'https://boothplorer.com/items'}?search=${encodeURIComponent(asset.name)}`));
  $('#openPath').addEventListener('click',()=>window.assetApi.openExternal(fileUrl(asset.fullPath)));
  if(storedBooth)$('#openStoredBooth').addEventListener('click',()=>window.assetApi.openExternal(storedBooth));
  $('#applyBoothLink').addEventListener('click',async()=>{const link=$('#boothLinkInput').value.trim();if(!/^https:\/\/[^/]*booth\.pm\/.*items\/\d+/i.test(link)){ $('#scanStatus').textContent='请输入有效的 BOOTH 商品链接'; return;} $('#boothCandidate').innerHTML='<span class="detail-label">BOOTH / FETCHING</span><p>正在下载商品信息和预览图…</p>';const result=await window.assetApi.boothSearch(link);asset.booth=result;await window.assetApi.saveClassifications(state.root,state.assets);renderGrid();renderDossier();});
  $('#saveCategory').addEventListener('click',async()=>{ asset.category=$('#categorySelect').value; await window.assetApi.saveClassifications(state.root,state.assets); $('#scanStatus').textContent=`SAVED / ${asset.category}`; renderGrid(); renderDossier(); });
  $('#saveLink').addEventListener('click',async()=>{const link=$('#externalLink').value.trim();if(!/^https?:\/\//i.test(link))return;asset.links=[...new Set([...(asset.links||[]),link])];await window.assetApi.saveClassifications(state.root,state.assets);$('#scanStatus').textContent='LINK SAVED';});
  $('#saveRelation').addEventListener('click',async()=>{asset.parentPath=$('#parentSelect').value||null;await window.assetApi.saveClassifications(state.root,state.assets);$('#scanStatus').textContent=asset.parentPath?'RELATION SAVED':'RELATION CLEARED';renderDossier();});
  if(parentAsset)$('#openParent').addEventListener('click',()=>{state.selected=parentAsset;renderGrid();renderDossier();});
  $('#requestMove').addEventListener('click',()=>{ state.pendingCategory=$('#categorySelect').value; $('#moveText').textContent=`“${asset.rawName}” 将从当前目录移动到 “${state.pendingCategory}”。此操作会改变原文件位置。`; $('#moveDialog').showModal(); });
}
async function scan() { $('#scanStatus').textContent='SCANNING…'; state.assets=await window.assetApi.scan(state.root); state.selected=null; renderGrid(); $('#dossier').innerHTML='<div class="empty"><span>SELECT / 选择素材</span><p>从左侧档案中选取一项，检查 BOOTH 候选和归档位置。</p></div>'; $('#scanStatus').textContent=`READY / ${state.assets.length} ITEMS`; }
$('#scan').addEventListener('click',scan); $('#chooseRoot').addEventListener('click',async()=>{ const folder=await window.assetApi.chooseRoot(); if(folder){state.root=folder;$('#rootName').textContent=folder;scan();} });
$('#classifyAll').addEventListener('click', async () => { const targets = state.assets.filter(asset => !asset.booth && !asset.isOrganized); if (!targets.length) { $('#scanStatus').textContent='NO UNORGANIZED ITEMS TO CHECK'; return; } $('#classifyAll').disabled=true; let moved=0; let manual=0; for (let index=0; index<targets.length; index++) { const asset=targets[index]; $('#scanStatus').textContent=`BOOTH CHECK ${index + 1}/${targets.length} / ${asset.rawName}`; try { const result=await window.assetApi.boothSearch(asset.name); asset.booth=result; if (result.matched) { const title = (result.title || '').toLowerCase(); asset.category=title.includes('hair') || title.includes('髪') || title.includes('ヘア') ? '03_头发' : title.includes('makeup') || title.includes('メイク') || title.includes('化粧') ? '04_妆容' : title.includes('outfit') || title.includes('衣装') || title.includes('服装') ? '02_衣服' : title.includes('plugin') || title.includes('system') || title.includes('tool') || title.includes('ツール') || title.includes('ギミック') || title.includes('shader') ? '05_功能插件' : title.includes('avatar') || title.includes('アバター') ? '06_Avatar本体' : title.includes('world') || title.includes('ワールド') ? '07_场景与地图' : title.includes('texture') || title.includes('material') || title.includes('テクスチャ') ? '08_贴图与材质' : '01_道具'; $('#scanStatus').textContent=`MOVING ${index + 1}/${targets.length} / ${asset.rawName}`; const moveResult=await window.assetApi.moveAsset(asset,asset.category); asset.fullPath=moveResult.target; asset.isOrganized=true; moved++; } else { asset.category='91_非VRC内容'; manual++; } } catch { asset.category='91_非VRC内容'; asset.booth={matched:false,status:'检索失败，等待手动确认'}; manual++; } renderGrid(); } await window.assetApi.saveClassifications(state.root,state.assets); $('#classifyAll').disabled=false; state.selected=null; await scan(); $('#scanStatus').textContent=`COMPLETE / MOVED ${moved} · MANUAL ${manual}`; });
document.querySelectorAll('.rail-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.rail-btn.active').classList.remove('active');btn.classList.add('active');state.filter=btn.dataset.filter;renderGrid();}));
$('#filter').addEventListener('input',e=>{state.query=e.target.value;renderGrid();});
let droppedPaths=[];let dragDepth=0;
const dropOverlay=$('#dropOverlay');
document.addEventListener('dragenter',event=>{event.preventDefault();dragDepth++;if(event.dataTransfer?.types.includes('Files'))dropOverlay.classList.add('active');});
document.addEventListener('dragover',event=>event.preventDefault());
document.addEventListener('dragleave',event=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)dropOverlay.classList.remove('active');});
document.addEventListener('drop',event=>{event.preventDefault();dragDepth=0;dropOverlay.classList.remove('active');droppedPaths=[...event.dataTransfer.files].map(file=>window.assetApi.getDroppedPath(file)).filter(path=>/\.(zip|rar|7z|unitypackage)$/i.test(path));if(!droppedPaths.length){$('#scanStatus').textContent='仅支持 ZIP、RAR、7Z、Unity Package';return;}const target=categoryOptions.includes(state.filter)?`“${state.filter}”分类页`:'“待整理”页';$('#importText').textContent=`将 ${droppedPaths.length} 个文件导入到${target}。选择“移动”会移动原文件；选择“复制”会保留原文件。`;$('#importDialog').showModal();});
$('#cancelImport').addEventListener('click',()=>$('#importDialog').close());
async function importDropped(mode){const button=mode==='move'?$('#moveImport'):$('#copyImport');button.disabled=true;try{const target=categoryOptions.includes(state.filter)?state.filter:'';const imported=await window.assetApi.importAssets(droppedPaths,state.root,mode,target);$('#importDialog').close();await scan();if(target){state.assets.filter(asset=>imported.includes(asset.fullPath)).forEach(asset=>{asset.category=target;asset.confirmed=true;});await window.assetApi.saveClassifications(state.root,state.assets);}$('#scanStatus').textContent=`IMPORTED / ${imported.length} FILES`;}catch(error){window.alert(`导入失败：${error.message}`);}finally{button.disabled=false;droppedPaths=[];}}
$('#moveImport').addEventListener('click',()=>importDropped('move'));$('#copyImport').addEventListener('click',()=>importDropped('copy'));
document.addEventListener('click',event=>{const pick=event.target.closest('.candidate-pick');if(pick&&!window.confirm('确认使用这个 BOOTH 候选封面吗？')){event.preventDefault();event.stopImmediatePropagation();return;}if(event.target.closest('.candidate-pick,#boothSearch,#applyBoothLink')&&state.selected)state.selected.useDefaultCover=false;},true);
$('#llmSettings').addEventListener('click',async()=>{ const data=await window.assetApi.getLlmSettings(); const s=data.settings; $('#llmEnabled').checked=s.enabled; $('#llmEndpoint').value=s.endpoint; $('#llmModel').value=s.model; $('#llmApiKey').value=s.apiKey; $('#llmVision').checked=s.useVision; $('#debugPaths').textContent=`配置：${data.configPath}\n日志：${data.logsPath}`; $('#llmTestResult').textContent=''; $('#settingsDialog').showModal(); });
function readLlmForm(){return {enabled:$('#llmEnabled').checked,endpoint:$('#llmEndpoint').value.trim(),model:$('#llmModel').value.trim(),apiKey:$('#llmApiKey').value.trim(),useVision:$('#llmVision').checked};}
$('#saveLlm').addEventListener('click',async()=>{await window.assetApi.saveLlmSettings(readLlmForm());$('#llmTestResult').textContent='设置已保存。';});
$('#testLlm').addEventListener('click',async()=>{await window.assetApi.saveLlmSettings(readLlmForm());$('#llmTestResult').textContent='正在测试…';const result=await window.assetApi.testLlm();$('#llmTestResult').textContent=result ? `测试结果：${JSON.stringify(result)}` : '测试未运行：请确认已启用并填写 API 密钥。';});
$('#openLogs').addEventListener('click',async()=>{const data=await window.assetApi.getLlmSettings();await window.assetApi.openLocalPath(data.logsPath);});
  $('#cancelMove').addEventListener('click',()=>$('#moveDialog').close());
  $('#confirmMove').addEventListener('click',async(e)=>{e.preventDefault(); const asset=state.selected; if(!asset)return; const button=$('#confirmMove'); button.disabled=true; button.textContent='正在移动…'; try { const previousPath=asset.fullPath; const result=await window.assetApi.moveAsset(asset,state.pendingCategory); asset.fullPath=result.target; asset.category=state.pendingCategory; asset.isOrganized=true; asset.confirmed=true; state.assets.forEach(item=>{if(item.parentPath===previousPath)item.parentPath=result.target;}); await window.assetApi.saveClassifications(state.root,state.assets); $('#moveDialog').close(); $('#scanStatus').textContent=`MOVED / ${result.target}`; await scan(); } catch(error){$('#scanStatus').textContent=`MOVE FAILED / ${error.message}`; $('#moveDialog').close(); window.alert(`移动失败：${error.message}\n\n文件：${asset.fullPath}\n目标分类：${state.pendingCategory}`);} finally { button.disabled=false; button.textContent='确认并移动'; } });
scan();
